# -*- coding: utf-8 -*-
"""Python_Data_Structures_Exercises

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ZjGg0Xnmo5skeLBG8Eqe1fZqZu6Pvww_

# Task
Implemente três algoritmos em Python: um para manipular uma lista de filmes favoritos (criar lista, adicionar 5 filmes solicitados ao usuário com `while`, imprimir com `for` e `enumerate`), um para manipular um dicionário de material escolar (criar dois dicionários, adicionar 5 itens solicitados ao usuário com `while` no segundo, atualizar o primeiro com `update`, imprimir com `for`), e um para manipular um sistema de cadastro de alunos (usar lista para dados, dicionário para associar matrícula aos dados, cadastrar 5 alunos solicitados ao usuário, imprimir dados e matrícula).

## Lista de Filmes Favoritos

Este código cria uma lista de filmes, solicita 5 nomes ao usuário usando um while e, em seguida, imprime cada filme com sua posição na lista usando 'for' e 'enumerate()'.
"""

def filmes_interativos():
    filmes = []
    print('Adicione 5 filmes favoritos')
    while len(filmes) < 5:
        nome = input(f'Digite o nome do filme #{len(filmes) + 1}: ').strip()
        if nome:
            filmes.append(nome)
        else:
            print('Entrada vazia. Digite um nome válido.')

    print('\nSeus filmes favoritos:')
    for pos, filme in enumerate(filmes, start=1):
        print(f'{pos}. {filme}')

filmes_interativos()

"""## Lista de Material Escolar (Dicionários)

Este código cria dois dicionários, preenche o primeiro com 3 itens iniciais, solicita 5 novos itens ao usuário para preencher o segundo dicionário usando um `while` atualiza o primeiro com o conteúdo do segundo e, finalmente, imprime todos os itens usando um `for`.

"""

material_escolar_base = {}
material_escolar_base = {
    "101": "Caderno",
    "102": "Lápis",
    "103": "Borracha"
}
novos_itens = {}
print("--- Entrada de Novos Materiais ---")
print("O dicionário base já possui 3 itens. Adicione 5 novos materiais.")

limite_adicionais = 5

while len(novos_itens) < limite_adicionais:
    indice = len(novos_itens) + 1
    print("-" * 25)

    # 3. Código do produto (chave do dicionário)
    codigo = input(f"Digite o CÓDIGO do {indice}º novo item: ").strip()

    # 3. Tipo do material (valor do dicionário)
    tipo = input(f"Digite o TIPO do {indice}º novo item: ").strip()

    # Adição de uma validação extra (sua melhoria)
    if codigo and tipo:
        # Verifica se o código já está em uso para evitar sobrescrever
        if codigo in material_escolar_base or codigo in novos_itens:
            print(f"Código '{codigo}' já existe! Por favor, insira um código único.")
            continue # Volta para o início do loop sem incrementar

        novos_itens[codigo] = tipo
        print(f"Item '{tipo}' adicionado com sucesso.")
    else:
        print("Entrada inválida. O código e o tipo não podem ser vazios.")

# 4. Atualize o primeiro dicionário com o conteúdo do segundo (usar a função update());
material_escolar_base.update(novos_itens)

print("\nLista Completa de Material Escolar (Base + Novos)")
print(f"Total de Itens Cadastrados: {len(material_escolar_base)}")

# 5. Posteriormente imprima todos os elementos da lista (usar o comando for).
for codigo, tipo in material_escolar_base.items():
    print(f"**Código:** {codigo} | **Tipo:** {tipo}")

"""## Cadastro de Aluno (Lista e Dicionário)

Este código utiliza uma estrutura de lista para temporariamente armazenar dados de um aluno e uma estrutura de dicionário principal para armazenar os dados de todos os alunos, utilizando a matrícula como chave. Ele cadastra 5 alunos e, em seguida, imprime os dados de todos.

"""

cadastro_alunos = {}
alunos_registrados = 0

print("Sistema de Cadastro de Alunos")

while alunos_registrados < 5:
    print(f"\nCadastro do Aluno #{alunos_registrados + 1}")

    while True:
        matricula = input("Digite o número de MATRÍCULA do aluno: ").strip()
        if not matricula:
            print("Matrícula não pode ser vazia.")
        elif matricula in cadastro_alunos:
            print(f" A matrícula {matricula} já está cadastrada. Digite outra.")
        else:
            break
    nome = input("Digite o NOME do aluno: ").strip()
    sobrenome = input("Digite o SOBRENOME do aluno: ").strip()
    email = input("Digite o E-MAIL do aluno: ").strip()

    # Garantir que todos os campos obrigatórios foram preenchidos
    if nome and sobrenome and email:
        # AQUI usamos um Dicionário para os dados do aluno (Melhoria)
        dados_aluno = {
            "nome": nome,
            "sobrenome": sobrenome,
            "email": email
        }

        # Adiciona o aluno ao dicionário principal
        cadastro_alunos[matricula] = dados_aluno
        alunos_registrados += 1
        print(f" Aluno {nome} cadastrado com sucesso!")
    else:
        print(" Entrada inválida. Nome, Sobrenome e Email são obrigatórios.")

print("\n--- Dados Finais dos Alunos Cadastrados ---")
# Imprima os dados de todos dos alunos e sua matrícula (usando for)
for matricula, dados in cadastro_alunos.items():
    print("-" * 35)
    print(f"**MATRÍCULA:** {matricula}")
    # Acesso mais legível usando chaves do dicionário aninhado (Melhoria)
    print(f"  Nome: {dados['nome']}")
    print(f"  Sobrenome: {dados['sobrenome']}")
    print(f"  Email: {dados['email']}")